import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/footer";

import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background font-sans flex flex-col min-h-dvh",
          inter.className
        )}
      >
        <Header className="flex-shrink-0"></Header>
        <div className="container flex-1 pt-6 pb-14">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
